# fly.toml app configuration file generated for zs-store-sync on 2026-06-23T20:06:30+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zs-store-sync'
primary_region = 'sin'

[build]

[env]
  PORT = '3000'
  SCOPES = 'read_content,read_files,read_metaobject_definitions,read_metaobjects,read_products,write_content,write_files,write_metaobject_definitions,write_metaobjects,write_products'
  SHOPIFY_APP_URL = 'https://zs-store-sync.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
